# 18. Criação de vetores e arrays e numpy.random

In [2]:
import numpy as np

In [3]:
minha_lista = [1,2,3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[123], [456], [789]]

In [6]:
np.array(minha_matriz)

array([[123],
       [456],
       [789]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr = np.zeros((5,5))

In [11]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [15]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [17]:
np.random.rand(5)

array([0.08098672, 0.02271702, 0.39050506, 0.15637812, 0.08778962])

In [18]:
np.random.rand(5) * 100

array([52.00657204, 34.59247184, 53.36511022, 78.1046933 , 61.31330492])

In [19]:
    np.random.rand(5, 4)

array([[0.32647772, 0.49616797, 0.00771447, 0.3253319 ],
       [0.81027829, 0.14375256, 0.02402188, 0.27783406],
       [0.0893604 , 0.76156959, 0.82013198, 0.8468938 ],
       [0.04755169, 0.34661497, 0.39004872, 0.19974157],
       [0.36814875, 0.29421171, 0.31258372, 0.86147154]])

In [20]:
    np.random.rand(5, 4, 3)

array([[[0.39753229, 0.21388897, 0.59753372],
        [0.54264453, 0.1083015 , 0.17266213],
        [0.63109963, 0.43100261, 0.02514474],
        [0.03435254, 0.76821169, 0.78528639]],

       [[0.39694911, 0.7457796 , 0.62620039],
        [0.06252533, 0.08718026, 0.93847123],
        [0.52283132, 0.00456858, 0.53412197],
        [0.51476961, 0.12136805, 0.67226166]],

       [[0.73548819, 0.10472477, 0.80724247],
        [0.77391104, 0.46109298, 0.19122181],
        [0.92393734, 0.23079323, 0.88597077],
        [0.50514445, 0.03439987, 0.71364778]],

       [[0.35923979, 0.49092355, 0.84115   ],
        [0.65059397, 0.34472596, 0.8638842 ],
        [0.90680435, 0.31429188, 0.54173445],
        [0.9246928 , 0.22389323, 0.36275867]],

       [[0.88263551, 0.17030301, 0.65647888],
        [0.64787518, 0.97723745, 0.42529698],
        [0.12072808, 0.74231124, 0.74369683],
        [0.40175389, 0.66531124, 0.81140485]]])

In [21]:
np.random.rand(5, 4, 4)

array([[[0.2135016 , 0.47618324, 0.60132807, 0.12055981],
        [0.79434121, 0.1745409 , 0.40899208, 0.73434998],
        [0.88061842, 0.43726206, 0.68672347, 0.25447094],
        [0.82234239, 0.08971193, 0.63373396, 0.31695825]],

       [[0.70922303, 0.8674566 , 0.25482881, 0.61189921],
        [0.91010093, 0.2108975 , 0.78415363, 0.29328638],
        [0.66188589, 0.3320023 , 0.41995641, 0.15180565],
        [0.06890365, 0.40248362, 0.61227754, 0.42399742]],

       [[0.28628147, 0.23005222, 0.68447484, 0.23870586],
        [0.27178016, 0.15669758, 0.4805903 , 0.03381508],
        [0.72120552, 0.51601942, 0.68257565, 0.4349452 ],
        [0.76364543, 0.11615223, 0.05788486, 0.8175426 ]],

       [[0.98337598, 0.72844956, 0.20638628, 0.79187183],
        [0.39360333, 0.47781045, 0.65456389, 0.42386933],
        [0.29167958, 0.40316537, 0.33787679, 0.48291702],
        [0.59174277, 0.08931865, 0.39558773, 0.53102303]],

       [[0.4958438 , 0.23284431, 0.86352785, 0.09513993],
      

In [22]:
np.random.randn(4)

array([-0.754822  ,  1.70794289, -0.98128288,  0.2834311 ])

In [23]:
np.random.randint(0, 100, 10)

array([16, 18, 16, 87, 12, 65, 63, 73, 85, 21])

In [24]:
np.round(np.random.randint(0, 100, 10))

array([70, 11, 96, 63, 73, 68, 12, 18, 10, 72])

In [25]:
arr = np.random.rand(25)

In [26]:
arr

array([0.45144859, 0.91568225, 0.58225219, 0.30968099, 0.76601697,
       0.35724778, 0.56713236, 0.4131638 , 0.74406335, 0.67639544,
       0.73486275, 0.79256317, 0.65216012, 0.31779522, 0.92345645,
       0.99789814, 0.78097449, 0.16174523, 0.29014995, 0.93039373,
       0.07620922, 0.51874128, 0.61366923, 0.54284646, 0.84071421])

In [28]:
arr.reshape((5,5))

array([[0.45144859, 0.91568225, 0.58225219, 0.30968099, 0.76601697],
       [0.35724778, 0.56713236, 0.4131638 , 0.74406335, 0.67639544],
       [0.73486275, 0.79256317, 0.65216012, 0.31779522, 0.92345645],
       [0.99789814, 0.78097449, 0.16174523, 0.29014995, 0.93039373],
       [0.07620922, 0.51874128, 0.61366923, 0.54284646, 0.84071421]])

In [30]:
arr = arr.reshape((5,5))

In [31]:
arr

array([[0.45144859, 0.91568225, 0.58225219, 0.30968099, 0.76601697],
       [0.35724778, 0.56713236, 0.4131638 , 0.74406335, 0.67639544],
       [0.73486275, 0.79256317, 0.65216012, 0.31779522, 0.92345645],
       [0.99789814, 0.78097449, 0.16174523, 0.29014995, 0.93039373],
       [0.07620922, 0.51874128, 0.61366923, 0.54284646, 0.84071421]])

In [32]:
arr.shape

(5, 5)

In [33]:
arr.max()

0.9978981381931551

In [34]:
arr.min()

0.07620921554237525

In [36]:
arr.argmax()

15

In [1]:
arr.argmin()

NameError: name 'arr' is not defined

# 19. Indexação e Fatiamento de arrays

In [3]:
arr = np.arange(0, 30, 3)

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr[3]

9

In [7]:
arr[2:5]

array([ 6,  9, 12])

In [8]:
arr[:6]

array([ 0,  3,  6,  9, 12, 15])

In [9]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
arr[2:] = 100

In [11]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arr = np.arange(50).reshape((5, 10))

In [13]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
arr.shape

(5, 10)

In [15]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [16]:
arr[:][:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
arr2 = arr[:3]

In [19]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
arr2 = arr[:3].copy()

In [21]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
arr2[:] = 100

In [23]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [24]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [25]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [27]:
arr > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [28]:
arr = np.arange(0, 100)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
arr > 50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [31]:
bol = arr > 50

In [32]:
arr[bol]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
arr = np.linspace(0, 100, 30)

In [34]:
arr

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [35]:
arr.shape

(30,)

In [36]:
arr = arr.reshape(3, 10)

In [37]:
arr

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [38]:
arr[0:2, 2]

array([ 6.89655172, 41.37931034])