# 20. Funções de Ativação
## Sigmoid (função sigmoide) 
$y = \frac{1}{(1 + e ^ (-x))}$

## Hyperbolic tanget (função tangente hiperbólica)
$y = \frac{(e^x - e^(-x))}{(e ^ x + e ^ (-x))}$

Mais funções de Ativação
https://en.wikipedia.org/wiki/Activation_function

# 31. Descida do grandiente (gradient descent)
$d = y * (1 - y)$

# 33. Delta camada saída
$deltaSaida = erro * derivadaSigmoide$

# 35. Delta camada oculta
$deltaEscondida = derivadaSigmoide * peso * deltaSaida$

# 37. Backpropagation, taxa de aprendizagem e momento
$peso_{n+1}  = (peso_{n} * momento) + (entrada * delta * taxaDeAprendizagem)$

# 42. Implementação rede multicamada X

In [2]:
import numpy as np

def sigmoid(soma):
    return 1 / (1 + np.exp(-soma))

def sigmoidDerivada(sig):
    return sig * (1 - sig)

# a = sigmoid(0.5)
# b = sigmoidDerivada(a)

entradas = np.array([[0,0], [0,1], [1,0], [1,1]])
saidas = np.array([[0], [1], [1], [0]])

pesosX1 = [-0.424, -0.740, -0.961]
pesosX2 = [0.358, -0.577, -0.469]

pesos0 = np.array([pesosX1, pesosX2])

pesos1 = np.array([[-0.017,], [-0.893], [0.148]])

epocas = 1000000
taxaAprendizagem = 0.3
momento = 1
mediaAbsoluta = 0.0

for j in range(epocas):
    camadaEntrada = entradas
    somaSinapse0 = np.dot(camadaEntrada, pesos0)
    camadaOculta = sigmoid(somaSinapse0)

    somaSinapse1 = np.dot(camadaOculta, pesos1)
    camadaSaida = sigmoid(somaSinapse1)

    erroCamadaSaida = saidas - camadaSaida
    mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))    

    derivadaSaida = sigmoidDerivada(camadaSaida)
    deltaSaida = erroCamadaSaida * derivadaSaida

    pesos1Transposta = pesos1.T
    deltaSaidaXPeso = deltaSaida.dot(pesos1Transposta)

    deltaCamadaOculta = deltaSaidaXPeso * sigmoidDerivada(camadaOculta)

    camadaOcultaTransposta = camadaOculta.T
    pesosNovo1 = camadaOcultaTransposta.dot(deltaSaida)

    pesos1 = (pesos1 * momento) + (pesosNovo1 * taxaAprendizagem)
    
    camadaEntradaTransposta = camadaEntrada.T
    pesosNovo0 = camadaEntradaTransposta.dot(deltaCamadaOculta)

    pesos0 = (pesos0 * momento) + (pesosNovo0 * taxaAprendizagem)

print(f'Erro: {str(mediaAbsoluta)}')

Erro: 0.006978762880311359


In [2]:
saidas

NameError: name 'saidas' is not defined

In [8]:
camadaSaida

array([[0.00760694],
       [0.99401117],
       [0.994011  ],
       [0.00833029]])

# 43. Bias e erro
## mean square error (MSE) e Root mean square error (RMSE)

### Mean Square Error
$
MSE = \frac{1}{N} \sum_{i=1}^{N} (fi - yi)^{2}
$

### Root Mean Square Error
$
RSME = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (fi - yi)^{2}}
$

# 44. Saídas com mais neurônios e Deep learning
Estudos para aprofundamento:
- Redes neurais convulacionais
- Redes neurais recorrentes
- Keras, Theano, TensorFlow
- GPU

# 49. Base de dados breast cancer


In [3]:
import numpy as np
from sklearn import datasets

def sigmoid(soma):
    return 1 / (1 + np.exp(-soma))

def sigmoidDerivada(sig):
    return sig * (1 - sig)

base = datasets.load_breast_cancer()

# entradas = np.array([[0,0], [0,1], [1,0], [1,1]])
# saidas = np.array([[0], [1], [1], [0]])

entradas = base.data
valoresSaida = base.target
saidas = np.empty([569, 1], dtype=int)

for i in range(569):
    saidas[i] = valoresSaida[i]

pesos0 = 2 * np.random.random((30, 5)) - 1

pesos1 = 2 * np.random.random((5, 1)) - 1

epocas = 10000
taxaAprendizagem = 0.3
momento = 1
mediaAbsoluta = 0.0

for j in range(epocas):
    camadaEntrada = entradas
    somaSinapse0 = np.dot(camadaEntrada, pesos0)
    camadaOculta = sigmoid(somaSinapse0)

    somaSinapse1 = np.dot(camadaOculta, pesos1)
    camadaSaida = sigmoid(somaSinapse1)

    erroCamadaSaida = saidas - camadaSaida
    mediaAbsoluta = np.mean(np.abs(erroCamadaSaida))    

    derivadaSaida = sigmoidDerivada(camadaSaida)
    deltaSaida = erroCamadaSaida * derivadaSaida

    pesos1Transposta = pesos1.T
    deltaSaidaXPeso = deltaSaida.dot(pesos1Transposta)

    deltaCamadaOculta = deltaSaidaXPeso * sigmoidDerivada(camadaOculta)

    camadaOcultaTransposta = camadaOculta.T
    pesosNovo1 = camadaOcultaTransposta.dot(deltaSaida)

    pesos1 = (pesos1 * momento) + (pesosNovo1 * taxaAprendizagem)
    
    camadaEntradaTransposta = camadaEntrada.T
    pesosNovo0 = camadaEntradaTransposta.dot(deltaCamadaOculta)

    pesos0 = (pesos0 * momento) + (pesosNovo0 * taxaAprendizagem)

print(f'Erro: {str(mediaAbsoluta)}')

Erro: 0.3725834797891076


# 50. Redes neurais com pybrain

In [1]:
from pybrain.structure import FeedForwardNetwork
from pybrain.structure import LinearLayer, SigmoidLayer, BiasUnit
from pybrain.structure import FullConnection

rede = FeedForwardNetwork()

camadaEntrada = LinearLayer(2)
camadaOculta = SigmoidLayer(3)
camadaSaida = SigmoidLayer(1)

bias1 = BiasUnit()
bias2 = BiasUnit()

rede.addModule(camadaEntrada)
rede.addModule(camadaOculta)
rede.addModule(camadaSaida)
rede.addModule(bias1)
rede.addModule(bias2)

entradaOculta = FullConnection(camadaEntrada, camadaOculta)
saidaOculta = FullConnection(camadaOculta, camadaSaida)
biasOculta = FullConnection(bias1, camadaOculta)
biasSaida = FullConnection(bias2, camadaSaida)

rede.sortModules()

print(rede)
print(entradaOculta.params)
print(saidaOculta.params)
print(biasOculta.params)
print(biasSaida.params)




FeedForwardNetwork-10
   Modules:
    [<BiasUnit 'BiasUnit-6'>, <BiasUnit 'BiasUnit-8'>, <LinearLayer 'LinearLayer-5'>, <SigmoidLayer 'SigmoidLayer-7'>, <SigmoidLayer 'SigmoidLayer-9'>]
   Connections:
    []

[-1.18740976  2.04417565  0.2300093   0.21449455  1.00654436  1.34097646]
[ 1.16104962 -2.41223937 -0.47924254]
[ 0.40005592 -1.65366373 -0.42077427]
[-1.17705208]
